# Generated by Django 6.0.5 on 2026-06-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("rank", models.PositiveIntegerField(unique=True)),
                ("response_minutes", models.PositiveIntegerField()),
                ("resolution_minutes", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name_plural": "Priorities",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="EscalationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "to_level",
                    models.CharField(
                        choices=[("hos", "HOS"), ("hod", "HOD")], max_length=4
                    ),
                ),
                ("threshold_minutes", models.PositiveIntegerField()),
                ("order", models.PositiveIntegerField()),
                (
                    "priority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation_rules",
                        to="sla.priority",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("priority", "to_level"),
                        name="unique_escalation_rule_per_priority_level",
                    ),
                    models.UniqueConstraint(
                        fields=("priority", "order"),
                        name="unique_escalation_rule_order_per_priority",
                    ),
                ],
            },
        ),
    ]
