"""
Django settings for resolver project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
from dotenv import load_dotenv

from pathlib import Path

from tickets.apps import TicketsConfig

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-evo47-7z$&aazzyp7_cqf85%!q2)wsrw*lb)+3ab9+$0%h6(=5'
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
# Application definition

INSTALLED_APPS = [
    # Modern admin interface (must be before django.contrib.admin)
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # add tickets app
    "tickets.apps.TicketsConfig",
    # add django rest framework
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    # add CORS headers
    "corsheaders",
    # add whitenoise for static files
    "whitenoise.runserver_nostatic",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",  # For DRF web interface
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}


AUTH_USER_MODEL = "tickets.CustomUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add whitenoise for static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Add CORS middleware (must be before CommonMiddleware)
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "resolver.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "resolver.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL if available (Render), otherwise use individual env vars
if os.getenv("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Explicitly define static files finders (important for Django Unfold)
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Additional static files directories (if needed)
STATICFILES_DIRS = []

# WhiteNoise configuration - use simpler backend for Django Unfold
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Use CompressedStaticFilesStorage instead of CompressedManifestStaticFilesStorage
        # for better compatibility with Django Unfold
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# WhiteNoise settings for better static file serving
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_MANIFEST_STRICT = False  # Don't fail on missing files

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS Configuration
# Allow frontend running on localhost:5173 to make requests
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
#     "https://resolver-zeta.vercel.app",
# ]

CORS_ALLOWED_ORIGINS = os.getenv(
    "ALLOWED_ORIGINS",
    "http://localhost:5173, http://127.0.0.1:5173",
).split(",")

# Allow credentials (cookies, authorization headers, etc.)
CORS_ALLOW_CREDENTIALS = True

# Optional: Allow all origins in development (NOT recommended for production)
# CORS_ALLOW_ALL_ORIGINS = True

# Email Configuration for Magic Link Authentication
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)

# For production with SMTP
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@example.com")

# For development - emails will be printed to console
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Authentication Settings
COMPANY_NAME = os.getenv("COMPANY_NAME", "Django Resolver")
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

# Session and Token Configuration
TOKEN_EXPIRY_HOURS = {
    "technician": 24 * 30,  # 30 days for frequent users
    "default": 8,  # 8 hours for regular users
    "remember_me": 24 * 30,  # 30 days when remember me is checked
}

# Magic Link Configuration
MAGIC_LINK_EXPIRY_MINUTES = 15
# Django Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "Django Resolver",
    "SITE_HEADER": "Maintenance Ticket Management",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "🔧",  # Wrench emoji for maintenance theme
        "dark": lambda request: "🔧",
    },
    "SITE_SYMBOL": "speed",  # Material icon for dashboard
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "ENVIRONMENT": "resolver.settings.environment_callback",
    "DASHBOARD_CALLBACK": "resolver.settings.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Ticket Management",
                "icon": "confirmation_number",
                "items": [
                    {
                        "title": "All Tickets",
                        "icon": "list",
                        "link": lambda request: "/admin/tickets/ticket/",
                        "badge": "resolver.settings.active_tickets_badge",
                    },
                    {
                        "title": "Open Tickets",
                        "icon": "report_problem",
                        "link": lambda request: "/admin/tickets/ticket/?status__exact=open",
                    },
                    {
                        "title": "Assigned",
                        "icon": "assignment_ind",
                        "link": lambda request: "/admin/tickets/ticket/?status__exact=assigned",
                    },
                    {
                        "title": "In Progress",
                        "icon": "autorenew",
                        "link": lambda request: "/admin/tickets/ticket/?status__exact=in_progress",
                    },
                    {
                        "title": "Pending",
                        "icon": "schedule",
                        "link": lambda request: "/admin/tickets/ticket/?status__exact=pending",
                    },
                ],
            },
            {
                "title": "Resources",
                "icon": "category",
                "items": [
                    {
                        "title": "Sections",
                        "icon": "workspaces",
                        "link": lambda request: "/admin/tickets/section/",
                    },
                    {
                        "title": "Facilities",
                        "icon": "business",
                        "link": lambda request: "/admin/tickets/facility/",
                    },
                ],
            },
            {
                "title": "User Management",
                "icon": "people",
                "items": [
                    {
                        "title": "All Users",
                        "icon": "person",
                        "link": lambda request: "/admin/tickets/customuser/",
                    },
                    {
                        "title": "Technicians",
                        "icon": "engineering",
                        "link": lambda request: "/admin/tickets/customuser/?role__exact=technician",
                    },
                    {
                        "title": "Managers",
                        "icon": "admin_panel_settings",
                        "link": lambda request: "/admin/tickets/customuser/?role__exact=manager",
                    },
                ],
            },
            {
                "title": "Engagement",
                "icon": "forum",
                "items": [
                    {
                        "title": "Comments",
                        "icon": "comment",
                        "link": lambda request: "/admin/tickets/comment/",
                    },
                    {
                        "title": "Feedback",
                        "icon": "star",
                        "link": lambda request: "/admin/tickets/feedback/",
                    },
                ],
            },
        ],
    },
}


def environment_callback(request):
    """Show environment badge in admin"""
    import os
    if os.getenv("DEBUG", "True") == "True":
        return ["Development", "success"]
    return ["Production", "danger"]


def active_tickets_badge(request):
    """Show count of active tickets in sidebar"""
    from tickets.models import Ticket
    count = Ticket.objects.exclude(status__in=['resolved', 'closed']).count()
    return count


def dashboard_callback(request, context):
    """Custom dashboard widgets"""
    from tickets.models import Ticket, CustomUser, Section, Facility
    from django.db.models import Count, Q
    from django.utils import timezone
    from datetime import timedelta

    # Calculate key metrics
    total_tickets = Ticket.objects.count()
    active_tickets = Ticket.objects.exclude(
        status__in=['resolved', 'closed']).count()
    resolved_today = Ticket.objects.filter(
        resolved_at__date=timezone.now().date()
    ).count()

    # Overdue tickets (>7 days old and not resolved)
    overdue_date = timezone.now() - timedelta(days=7)
    overdue_tickets = Ticket.objects.filter(
        created_at__lt=overdue_date,
        status__in=['open', 'assigned', 'in_progress', 'pending']
    ).count()

    # Status breakdown
    status_stats = Ticket.objects.values('status').annotate(count=Count('id'))

    # Top sections by ticket count
    section_stats = Section.objects.annotate(
        ticket_count=Count('ticket')
    ).order_by('-ticket_count')[:5]

    context.update({
        "kpi": [
            {
                "title": "Total Tickets",
                "metric": total_tickets,
                "description": "All time",
                "icon": "confirmation_number",
            },
            {
                "title": "Active Tickets",
                "metric": active_tickets,
                "description": "Currently open",
                "icon": "pending_actions",
                "color": "orange" if active_tickets > 10 else "green",
            },
            {
                "title": "Resolved Today",
                "metric": resolved_today,
                "description": timezone.now().strftime("%B %d"),
                "icon": "check_circle",
                "color": "green",
            },
            {
                "title": "Overdue",
                "metric": overdue_tickets,
                "description": ">7 days old",
                "icon": "warning",
                "color": "red" if overdue_tickets > 0 else "green",
            },
        ],
        "status_breakdown": list(status_stats),
        "top_sections": section_stats,
    })

    return context
