# Generated by Django 6.0.5 on 2026-07-15 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0001_initial"),
        ("tickets", "0002_add_ticket_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "campus_department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_sequence",
                        to="org.campusdepartment",
                    ),
                ),
            ],
        ),
    ]
