# Generated by Django 6.0.5 on 2026-06-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("org", "0001_initial"),
        ("sla", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location_details",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the ticket creation wizard should collect location information.",
                    ),
                ),
                (
                    "default_priority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_categories",
                        to="sla.priority",
                    ),
                ),
                (
                    "section_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_categories",
                        to="org.sectiontype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Service Categories",
                "ordering": ["section_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_items",
                        to="catalog.servicecategory",
                    ),
                ),
                (
                    "default_priority",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional item-level priority override; falls back to category default when null.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_items",
                        to="sla.priority",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="servicecategory",
            constraint=models.UniqueConstraint(
                fields=("section_type", "name"),
                name="unique_service_category_per_section_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceitem",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="unique_service_item_per_category"
            ),
        ),
    ]
