# Generated by Django 5.2.6 on 2025-09-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(blank=True, choices=[('building', 'Building'), ('ict', 'ICT Equipment'), ('laundry', 'Laundry Equipment'), ('kitchen', 'Kitchen Equipment'), ('residential', 'Residential')], max_length=50, null=True),
        ),
    ]
