# Generated by Django 5.2.7 on 2025-10-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_facility_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sections_specialized_in',
            field=models.ManyToManyField(blank=True, help_text='Sections the technician is specialized in.', related_name='technicians', to='tickets.section'),
        ),
    ]
