# Generated by Django 6.0.5 on 2026-06-27 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtime", "0001_initial"),
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ticket_created", "Ticket Created"),
                            ("ticket_assigned", "Ticket Assigned"),
                            ("ticket_status_changed", "Ticket Status Changed"),
                            ("ticket_escalated", "Ticket Escalated"),
                            ("ticket_resolved", "Ticket Resolved"),
                            ("comment_added", "Comment Added"),
                            ("sla_warning", "SLA Warning"),
                            ("sla_breach", "SLA Breach"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("body", models.CharField(max_length=256)),
                ("ticket_no", models.CharField(blank=True, max_length=24)),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "realtime_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "read"], name="realtime_no_user_id_e518b5_idx"
                    )
                ],
            },
        ),
    ]
